### ISSUE TITLE
SUGGESTION: GUI improvements

### ISSUE THREAD

**Issue by AlonDan** [Zarxrax/Cutie-Roto#1]
I've tried Cutie and now Cutie-Roto which is so much simple to install, thank you so much for your great work!

I have some GUI suggestions to make it even more user-friendly:

---
**Cutie-Roto Launcher**

- Drag & Drop file to the Video / Source
Instead of manually select file via browsing

- Remember latest used "Worker Folder" path
 And a checkbox option (by default) to DELETE older existing Sub-Folders and Files so it will be possible to Re-Use the same Workspace Folder instead of creating new one every time.
That way, the OUTPUT files will be always in the same path directory and sub-folders.
 
- Remember last configurations on the Launcher, any options, path, remember latest used one will be to test in different sessions.

- Remember last used EXPORT settings (easy for re-use)
Currently closing the EXPORT window pop up will reset it's last used settings.
 
---
**GENERAL Cutie-Roto GUI improvements:**
 
- Mouse Scroll Wheel: up = ZOOM-IN   down = ZOOM-OUT 
 
- A mode to allow to SHOW / HIDE the ADD/REMOVE points markers on the large view
It will be easier to edit, remove, add when they are visible, but also HIDE to preview clean result while editing.

- **UNDO / REDO** will make a HUGE change in the workflow! 

- Overlay Mode Extra options for P**REVIEW** within Cutie-ROTO: 
- RGBA will be nice to see as final result
- Control and PREVIEW Refine Edges before export, example:
**ADD** or **SUBTRAUCT** 1 pixel or more from the mask edges (user can choose the amount)

This is usually done within composite softwares to get rid of extra mask pixels for cleanup, it will be nice to have it built in to Cutie-ROTO.

- Choose a temporary **Background** for testing Preview / Export:
- Import PNG / JPG and allow to stretch to fit the preview 
- Green Screen (or choose any custom solid color)

- If in the future there will be no need for a Launcher, so the Launcher files will be built-in to the actual Main Application it will be so much easier and user-friendly.
 
 ---
 
💡 I have so many other ideas to improve (GUI / Design) I'll be happy to help this AMAZING Project and I hope that you will consider some of my suggestions.

Keep up the good work, much love! 💙

**Comment by Zarxrax** [comment]
Hi, thanks for your feedback.
I am not very experienced at programming, so some of these might take me some time, or might not be possible for me to implement. If someone can contribute code it would be a big help. But, I'm continuing to add improvements slowly but surely.

1. The launcher should currently remember the last used video/workspace. Does that not happen for you?
2. I'm hesitant to add delete functionality into the program because I don't want to mistakenly delete files that the user wants to keep. For instance, if they export a video into the workspace, or put some extra files into the workspace, should those be deleted if the user checks a box to delete the workspace files? Because of these questions, I just added a button to open the workspaces folder so the user can manually delete what they want. I will continue to consider this.
3. For mouse wheel zoom, do you mean in the minimap, or on the main window?
4. What overlay mode settings do you want to see in the preview?
5. FFV1 codec can export as RGBA.
6. Green screen option is there in export settings.

**Comment by AlonDan** [comment]
Thank you for your detailed reply!

1. I noticed that the launcher does remember last video after the first use.

The launcher is NOT remembering the last workspace:
After first run Workspace is always empty based on the "/src" directory and also it's not possible to change since it's locked.

2. For delete last project, you can just add to the Launcher:
- Checkbox: DELETE last project and OVERWRITE if any old sub-directories exist

Open workspaces folder is very helpful indeed, good job!
But still need an option to browse or create Workspace per project by browsing and not force creating Main Project directory ONLY on the main "/src" of the Cutie-Roto.

Like I mentioned above, at the moment Workspaces option is locked and cannot be changed.

3. For mouse wheel zoom, I think once you'll get rid of the mini-map it and add the POINTS I suggested (even before doing that) you can just use the Mouse Wheel to zoom in-out but another suggestion:
- Mouse Wheel UP/DOWN to zoom will be Faster (current speed you use)
- Mouse Wheel UP/DOWN + Shift will be slower (more accurate)

4. The actual **RGBA** mode will be GREAT on the Overlay / Preview:
- That means it will show the ORIGINAL IMAGE MASKED just like when you export to Composite + Alpha, that way you can see the final result WHILE still working on the sequence.
- It's not actually called an Overlay once you do that, so I would just change "Overlay" to "Preview Mode" which contain all the other modes currently using and if you'll add more in the future.

5. Exporting the RGBA should be 1st default option in my opinion, unless you'll add my early suggestion: REMEMBER last options, since export is resetting when closing it's window:
- Remember Last options will solve everything (when closed window, or the main software)

Currently it doesn't remember anything including the last used FPS and everything else.

---

Another suggestion I hope you'll consider:

When selecting a VIDEO file, I understand it splits to PNG Sequence when loading but if you can make the VIDEO FPS to be recognize AUTOMATICALLY and put in the PREVIEW (workspace) and on the EXPORT based on that import video source file it will be very useful.

Thanks again for your great work!
I'm looking forward for your improvements and extra features to come, I'll be happy to share more ideas to make Cutie-Roto even better 👍

**Comment by Zarxrax** [comment]
I just want to make sure I understand what you are saying about the workspace.

When I select a new video the first time, it automatically chooses the workspace folder name, and creates the workspace after I press Start.
![image](https://github.com/Zarxrax/Cutie-Roto/assets/16127268/92f49b7c-d008-4299-841f-7a2b579813c2)

Then, I close the application and start it again.
Now, the last used video file should automatically be selected, and the existing workspace should be automatically filled. To resume my previous work, I simply press the start button, without having to select anything:
![image](https://github.com/Zarxrax/Cutie-Roto/assets/16127268/e6775647-c7c2-4c34-8bcf-4dec7a42ad75)

So is this NOT happening for you?

**Comment by AlonDan** [comment]
So this is the thing, I just did exactly what you to test if I get the same:
1 - I loaded a video file
2 - Pressed Start
3 - Exit Cutie-Roto
4 - Loaded the Launcher again

What I get is that it won't show the last path like in your case, if I press START again it's fine, but it won't show the path... it's empty?

![python_2024-02-09_12-22-15](https://github.com/Zarxrax/Cutie-Roto/assets/21152334/de1226dd-f0a4-427f-9ff7-0330511c7010)

I guess it's fine as long as it works, but it's jut confusing.

Also, like I mentioned above, it will be nice to SELECT the Workspace Folder instead of put it under the SRC folder of the app root directory.

---
Another issue I found:
Since my Windows Theme is Dark, it's impossible to read the Tooltips inside Cutie-Roto, the text and background are light:

![python_2024-02-09_12-27-53](https://github.com/Zarxrax/Cutie-Roto/assets/21152334/ce3c4365-19e9-4b40-b7bb-7df3905fdd38)

I hope that this information helps, please keep up the good work! 👍

**Comment by Zarxrax** [comment]
Where did you extract the Cutie-roto application to? I wonder if it is having trouble reading or writing files in that location.
Your video file is in folder C:\TMP? Did you create that folder and load a file from there? Or is this a folder of temporary files that windows created?

As for being able to select the workspace folder, it should be relatively easy for me to add an option to change the base folder that all workspaces are saved in. That will need to wait until I have a more complete solution for saving and changing settings though. However I don't believe I will allow for changing workspaces for each individual clip, because that would add a lot of complexity.

For the tooltips issue, I assume you are using Windows 11? It looks like there is a bug in the theme with windows 11, but I found a workaround that someone posted. Could you please try the following?

In the file 'cutie_roto.py', change line 83 from:
`qdarktheme.setup_theme("auto")`
Change it to: 
`qdarktheme.setup_theme(theme="auto", additional_qss="QToolTip { border: 0px; }")`

Please let me know if that fixes the issue.

**Comment by AlonDan** [comment]
`Where did you extract the Cutie-roto application to?`
Full path is simple as: `D:\AI\Cutie-Roto-0.4.0\workspace\`
No block or anything with that drive, I have no issues with other apps or repositories.
I have no issues with other apps, but it's not going to be an issue once you'll allow to also choose WHERE the workspace path PER PROJECT or GLOBAL but at least allow to choose it will be very helpful.

---
`Your video file is in folder C:\TMP? Did you create that folder and load a file from there? Or is this a folder of temporary files that windows created?`

For the example I used `C:\TMP` but it doesn't matter if I use any other path, I tested on other drives and directories, same thing, but like I said... it's not actual an issue once you'll allow to choose the WORKSPACE per project or GLOBAL project path will be.

Even at the moment it doesn't matter much, it doesn't SHOW it until I START a project, the next LOAD which REMEMBER the last source project is shown on the launcher.

---

`For the tooltips issue, I assume you are using Windows 11?`
My bad, I forgot to mention that, I'm using Windows 10.

---

```
In the file 'cutie_roto.py', change line 83 from:
qdarktheme.setup_theme("auto")
Change it to:
qdarktheme.setup_theme(theme="auto", additional_qss="QToolTip { border: 0px; }")

Please let me know if that fixes the issue.
```

YES, that definatly helps, thank! 💙

**Comment by Zarxrax** [comment]
As of the newest release (0.4.6), a number of your requests have been implemented, or at least partially implemented.

A configuration file at cutie/config/gui_config.yaml can be modified to change a number of settings. In the future I would like to move the most useful options into a settings screen.

You can change the following and much more through the config file:
- the root workspace folder
- export settings
- refine edges settings

There is also a checkbox to delete the currently specified workspace from the launcher.
Also from the previous release I added preview overlay on color or background image, and drag and drop video into the launcher.

No one else I have spoken to has experienced your issue of the last workspace not automatically loading into the launcher, so I'm not sure what's going on there.

Next, I will probably work on saving data for individual workspaces, which will allow me to add your suggestion of copying the fps value from the input video into the export window.

**Comment by AlonDan** [comment]
Sounds GREAT!
I will check it out later and will share if I have more improvements ideas.

Keep up the good work! ❤

**Comment by AlonDan** [comment]
Dear +@Zarxrax I have some suggestions for the next update:

- Any REFINE EDGES controls will be nice, some examples:

1️⃣ - Control of where the refine edge will START: 

0 = From edge
-X (any number) = Subtract 1 pixel pre-edge
+X = (any number) = Add 1pixel post-edge

2️⃣ - Control the amount of Soft/Hard feathering of the refine edge
  
These are basic controls usually done in composite software such as Nuke, After Effects, etc.. so it will be nice to have it in the UI.

---

- If possible to add the REFINE EDGES to the **PREVIEW** so it will be easy to SEE it before exporting

- If there are any ways to improve the SEGMENT selection if it's a more advanced model, or add models specific for FULL BODY HUMAN, or Profile Human etc.. it will be nice.

All I know are some SAM models and the HIGHEST ONE usually needs lots of GPU VRAM but does an AMAZING JOB, very accurate in most cases.

So I don't know what you can add to the segmentation selection part, but if you have ideas to improve it via extra models or extra controls, **PLEASE DO**! 🙏

---

Of course, any of the above suggestions you're probably working on will be nice of course.
Thanks for your great work, I'll be happy to keep testing and let you know if I found an issue or if I have some nice suggestions to improve the UI/UX.

Keep up the good work!

**Comment by Zarxrax** [comment]
The new version has added undo support, and gets fps from the input video, among other additions.
