### ISSUE TITLE
Auto Clear VRAM

### ISSUE THREAD

**Issue by AlonDan** [Zarxrax/Cutie-Roto#2]
It seems like the Auto Clear VRAM works good with my old Nvidia GTX 980 4GB VRAM

But on Ultra, it will stop after some frames and the app is stuck, I must re-launch to continue.

Another thing,
It seems like ULTRA mode is superior and more accurate, is there a way to make it default or at least allow Cutie-Roto to REMEMBER last mode when closed.

I may suggested it already, 
It will be very useful to allow Cutie-Roto to REMEMBER any other properties for example Background Color or even last used loaded image, so when launching a new project it will use last used changes.

**Comment by Zarxrax** [comment]
Hi,
4GB VRAM is simply not enough for the ultra mode. You can try High quality instead, and see if it works, but even high quality might be limited to short clips for you. High quality should give a noticeable improvement from Normal. Ultra mode is probably just a small improvement from High.

You can set default settings by editing the file: cutie\config\gui_config.yaml

You can change the following line:
`default_quality: NormalQuality` to `default_quality: HighQuality`

And change:
`background_path: False` to the path for a background image, like `background_path: C:\test\file.png`

I eventually want to put a settings dialog so these settings can be changed directly in the application. But for now, you can edit this config file.

**Comment by AlonDan** [comment]
Thank you for the detailed reply, I will give that a try 👍
