### ISSUE TITLE
Fbgemm.dll missing? just a weird install bug or is this on my side? 

### ISSUE THREAD

**Issue by WeenieHutJr685** [Zarxrax/Cutie-Roto#5]
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\(insertname)\Downloads\Cutie-Roto-0.5.1\Cutie-Roto\python-3.11.7-embed-amd64\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

![image](https://github.com/user-attachments/assets/7203141d-6115-447e-ac91-15e5088c00f9)

**Comment by Zarxrax** [comment]
It looks like this issue may be introduced by the latest version of pytorch. I think downgrading pytorch to the previous version should fix it.

Please see the attached file. Extract install_dependencies.bat from the zip file and replace the existing one in the cutie-roto folder with this. Run install_dependencies.bat again and it will let you uninstall your existing version of torch and install the older version.

Let me know if that works.

[install_dependencies.zip](https://github.com/user-attachments/files/16560669/install_dependencies.zip)

**Comment by WeenieHutJr685** [comment]
Hey thank you, it works perfectly now.
